name: RedstoneClockDetector
main: com.gmail.tracebachi.RedstoneClockDetector.RedstoneClockDetector
version: ${project.version}
api-version: 1.13
author: Trace Bachi (tracebachi@gmail.com, BigBossZee)
commands:
  rcd:
    description: Main command for RedstoneClockDetector.
    usage: '/rcd <start|tp|list|reload>'
permissions:
  rcd:
    description: Gives access to the RCD command and messages.
    default: op
